/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/akita/Documents/GitHub/MandelbrotTang/al_ip/vram.v
 ** Date	:	2020 03 24
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module vram ( 
	dia, addra, cea, clka,
	dob, addrb, ceb, clkb
);

	output [2:0] dob;
	input  [2:0] dia;
	input  [16:0] addra;
	input  [16:0] addrb;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(3),
				.DATA_WIDTH_B(3),
				.ADDR_WIDTH_A(17),
				.ADDR_WIDTH_B(17),
				.DATA_DEPTH_A(131072),
				.DATA_DEPTH_B(131072),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({3{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule